### ISSUE TITLE
status isn't changing

### ISSUE THREAD

**Issue by egorsmkv** [Atrox/github-actions-badge#14]
I have added a badge to my repo here: https://github.com/egorsmkv/gh-actions-test

It seems like GitHub cached the picture and doesn't update it.

Maybe, this issue https://github.com/github/markup/issues/224 makes sense to this issue.

**Comment by egorsmkv** [comment]
Hmm, just added this issue and the badge turned to "SUCCESS" status. Is there a delay between this update?

I was seeing a "PENDING" badge about 3-4 minutes after completed successful build.

**Comment by Atrox** [comment]
Indeed :) shields.io caches the response for some minutes by default.

**Comment by egorsmkv** [comment]
Can we solve?

**Comment by Atrox** [comment]
You can override the cache settings for shields.io by settings `?cacheSeconds=3600` in the url but I think the cache does not matter that much.

**Comment by egorsmkv** [comment]
Thanks for help!
