### ISSUE TITLE
fail with isError

### ISSUE THREAD

**Issue by xmlking** [Atrox/github-actions-badge#17]
I have two repos one works, other other fails
both repos has GitHub Actions

```json
{"schemaVersion":1,"label":"GitHub Actions","message":"no runs","color":"inactive","isError":true,"namedLogo":"github","cacheSeconds":300}
```

works: https://github.com/xmlking/ngx-starter-kit
error: https://github.com/xmlking/micro-starter-kit

**Comment by Atrox** [comment]
You only have Actions setup on the develop branch - the check defaults to `master`. You can supply the parameter `ref` to customise which branch is getting checked. I just updated the [playground](https://actions-badge.atrox.dev/) with an option to specify the branch.

Could you try this out and report back to me if it works for you?

**Comment by xmlking** [comment]
Works 
Thanks

**Comment by xmlking** [comment]
badges status looks like working but when I click the button it is taking to wrong action # page. 
please test
https://github.com/xmlking/ngx-starter-kit
 https://github.com/xmlking/micro-starter-kit

**Comment by Atrox** [comment]
Oops, the `ref` parameter also has to be added to the `/goto` link. I just pushed a update to fix this in the [playground](https://actions-badge.atrox.dev/). Could you try it again?

[![Build Status](https://img.shields.io/endpoint.svg?url=https%3A%2F%2Factions-badge.atrox.dev%2Fxmlking%2Fmicro-starter-kit%2Fbadge%3Fref%3Ddevelop&style=flat)](https://actions-badge.atrox.dev/xmlking/micro-starter-kit/goto?ref=develop)
