### ISSUE TITLE
Support for private repos

### ISSUE THREAD

**Issue by jofftiquez** [Atrox/github-actions-badge#18]
How to add this badge to a private repo?

**Comment by Atrox** [comment]
The hosted version does not have access to your private repo. So you have to host a `github-actions-badge` instance for yourself and supply it with a `GITHUB_TOKEN` that has access to your private repositories.

**Comment by jofftiquez** [comment]
Perhaps a `?token=<Token>` query parameter to the url would be a nice feature to have. Like what CircleCI badge have.

**Comment by Atrox** [comment]
I just added this, thank you for the suggestion. Could you try it out to see if it works for you?
The [playground](https://actions-badge.atrox.dev/) now also has the option to specify a token.

**Comment by jofftiquez** [comment]
Wow! That's fast. Thanks a lot. I will test and give you feedback.
